### login
GET http://localhost:8081/12345/login

### notify score
POST http://localhost:8081/2/score?sessionkey=44f5d31b-cce7-4644-84db-f6e367433ae4
Content-Type: text/plain

35

### leaderboard
GET http://localhost:8081/2/highscorelist
