### login
GET http://localhost:8081/1234/login

### notify score
POST http://localhost:8081/2/score?sessionkey=ab0dce16-30d2-4fdf-8081-6a184303837e
Content-Type: text/plain

123002

### leaderboard
GET http://localhost:8081/2/highscorelist
